### ISSUE TITLE
Need help since last week, latest antimicro doesn't recognize controller having any buttons

### ISSUE THREAD

**Issue by michaelbianchini** [Ryochan7/antimicro-packaging#2]
Trying to run antimicro 2.21 64 bit, it does not recognize my controller as having any buttons asigned.  It recognizes the controller itself (since it doesn't show anything until the controller is plugged in).  Going to "Controller Mapping" and pushing buttons does not do anything ; same goes for "Quick Set".
![antimicro_issues](https://cloud.githubusercontent.com/assets/10685793/14585209/302a3414-043a-11e6-9f7d-f10f7faef51d.jpg)
I confirmed that "Hide Empty Buttons" is unchecked.  The controller is a Radio Shack Wired PC Controller.

The really strange thing is that this controller worked last week with a previous version of antimicro (2.20) but that version no longer runs on my PC, it crashes.

**Comment by Ryochan7** [comment]
This issue was reported in the old antimicro repository before I deleted it. SDL 2.0.4 changed how DirectInput joysticks are detected so anyone not using an XInput controller would have problems with antimicro version 2.21. The initial proposed change involved having to compile and bundle a custom version of SDL with antimicro to undo the change in SDL 2.0.4. However, there is a simpler fix that has been discovered since. Although unintentional on the SDL devs part, it really seems like there is an API change regarding SDL joystick support on Windows. A simple change to the SDL_Init call is actually all that is needed for DirectInput joysticks to work with SDL 2.0.4. Although, based on the documentation, the change should not be necessary since initializing SDL Game Controller support automatically initializes SDL joystick support and it was not necessary to explicitly use the SDL_INIT_JOYSTICK flag with older versions of SDL 2.

sdleventreader.cpp line 59:
```
SDL_Init(SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK);
```

**Comment by michaelbianchini** [comment]
Thank you so much! I really appreciate your help and getting this to work will enable lots of quality time for me and my wife. I will try it out and let you know.

**Comment by michaelbianchini** [comment]
I am struggling ; I am completely new to compiling and building executables in Windows, cmake, Qt, etc. I have tried following the instructions in README.md and have gotten as far as the CMake Wizard in Qt Creator.  Initially, I did not install MinGW as part of the Qt Creator install.  After I did this and deleted the cache and re-ran, I am getting the CMake Wizard and the Generator drop down is blank.

Here are the kit settings:
![image](https://cloud.githubusercontent.com/assets/10685793/14765583/32f6e3a0-09b6-11e6-8698-fd08f4456f45.png)
![image](https://cloud.githubusercontent.com/assets/10685793/14765585/540d8e7c-09b6-11e6-9a11-e2d0dd445f1c.png)
![image](https://cloud.githubusercontent.com/assets/10685793/14765588/6d625f56-09b6-11e6-97f2-c690cabaae78.png)
![image](https://cloud.githubusercontent.com/assets/10685793/14765593/83aa1f42-09b6-11e6-9456-2d1186815fb4.png)
![image](https://cloud.githubusercontent.com/assets/10685793/14765599/a1f0d3ba-09b6-11e6-8b86-23f1500fa95c.png)
![image](https://cloud.githubusercontent.com/assets/10685793/14765602/b42f99da-09b6-11e6-8169-d5601cb73326.png)


And here is my CMake Wizard:
![image](https://cloud.githubusercontent.com/assets/10685793/14765576/082dc2ba-09b6-11e6-98c1-1d788a8070bc.png)

Is

**Comment by ProfessorKaos64** [comment]
@Ryochan7 , pardon me interjecting, maybe I missed something, are you no longer going to develop Antimicro? :/

**Comment by jsbackus** [comment]
@michaelbianchini Still having trouble with this? If so, would you be willing to do some testing for us? If so, please join us at AntiMicro/antimicro#4.

**Comment by jsbackus** [comment]
@michaelbianchini I have created an installer with @Ryochan7's fix, if you would be willing to test it for me.

**Comment by michaelbianchini** [comment]
Will do - going on vacation this weekend so it will probably be after that
  Sent from IQTell - my Productivity app   From: Jeff Backus <notifications@github.com>
Sent: Sunday, May 29, 2016 11:42 AM
To: Ryochan7/antimicro-packaging <antimicro-packaging@noreply.github.com>
Cc: michaelbianchini <mike@michaelbianchini.com>; Mention <mention@noreply.github.com>
Subject: Re: [Ryochan7/antimicro-packaging] Need help since last week, latest antimicro doesn't recognize controller having any buttons (#2)


@michaelbianchini I have created an installer with @Ryochan7's fix, if you would be willing to test it for me.

**Comment by jsbackus** [comment]
@michaelbianchini Great! Thanks for checking it out when you get a chance!

**Comment by michaelbianchini** [comment]
@Ryochan7 IT WORKS! Sorry for taking so long, literally months, had lotsofli fe stuff going on. Anyway I wanted to thank you guys for the effort, I will always be able to map stuff now whenever we need it. Screenshot of happiness attached.
![working_antimicro](https://cloud.githubusercontent.com/assets/10685793/18809471/10e08930-824a-11e6-8d9d-e0bc5349342f.jpg)
