### ISSUE TITLE
crashing when loading a profile

### ISSUE THREAD

**Issue by apathy27** [Ryochan7/antimicro-packaging#3]
recently whenever i load a profile from the load option from a saved profile in a folder antimicro starts crashing. profiles that are already loaded (recently used) can be selected from the drop down in the upper left corner. but if i try to even make and save a new profile it crashes. I've already tried deleting and unpacking a new/fresh copy of antimicro but the issue still persists. I'm using antimicro 2.20 and tried 2.15 as well with which the above issue occurred

**Comment by Ryochan7** [comment]
Based on your problem, I would have thought it would have been related to multithreading problems in the application. However, version 2.15 should not have been affected by that type of problem. Multithreading problems were pretty much hammered out in version 2.21. You should try out the latest version of the application from the current maintainers and see if the problem has been fixed. If not, you should submit an issue at that repository.

https://github.com/AntiMicro/antimicro/releases/tag/2.22
